export const enum DataTestIdConfig {
    CHANGE_CONFIRM_PASSWORD = 'change-confirm-password',
    CHANGE_ENTRY_BUTTON = 'change-entry-button',
    CHANGE_PASSWORD = 'change-password',
    CHANGE_RETRY_BUTTON = 'change-retry-button',
    CHANGE_SUBMIT_BUTTON = 'change-submit-button',
    CHECK_BACK_BUTTON = 'check-back-button',
    CHECK_RETRY_BUTTON = 'check-retry-button',
    LOADER = 'loader',
    LOGIN_FORGOT_BUTTON = 'login-forgot-button',
    LOGIN_PASSWORD = 'login-password',
    LOGIN_REMEMBER = 'login-remember',
    LOGIN_RETRY_BUTTON = 'login-retry-button',
    LOGIN_SUBMIT_BUTTON = 'login-submit-button',
    REGISTRATION_CONFIRM_PASSWORD = 'registration-confirm-password',
    REGISTRATION_BACK_BUTTON = 'registration-back-button',
    REGISTRATION_ENTER_BUTTON = 'registration-enter-button',
    REGISTRATION_PASSWORD = 'registration-password',
    REGISTRATION_RETRY_BUTTON = 'registration-retry-button',
    REGISTRATION_SUBMIT_BUTTON = 'registration-submit-button',
    SIDER_SWITCH = 'sider-switch',
    SIDER_SWITCH_MOBILE = 'sider-switch-mobile',
    VERIFICATION_INPUT = 'verification-input',
}
