export const enum DateFormatConfig {
    FORMAT_DATE_TIME = 'HH:mm:ss',
    FORMAT_DAY_WEEK = 'dddd',
    FORMAT_DD_MM_YYYY_DASHED = 'DD-MM-YYYY',
    FORMAT_DD_MN_YYYY_DOT = 'DD.MM.YYYY',
    FORMAT_DD_MM_DOT = 'DD.MM',
    FORMAT_MONTH = 'MM-YYYY',
    FORMAT_WEEK = 'wo-YYYY',
    FORMAT_YYYY_MM_DD_DASHED = 'YYYY-MM-DD',
    LANG_FORMAT_DATE = 'D/M/YYYY',
    LANG_FORMAT_DAY = 'D',
    LANG_FORMAT_MONTH = 'MMMM',
    LANG_FORMAT_YEAR = 'YYYY',
}
