export const enum EventApiConfig {
    CHANGE_PASSWORD = 'authentification/change-password',
    CHECK_EMAIL = 'authentification/check-email',
    CONFIRM_EMAIL = 'authentification/confirm-email',
    FEEDBACK_ADD = 'feddback/add',
    FEEDBACKS_GET = 'feedbacks/get',
    INVALIDATE_ACCESS_TOKEN = 'session/invalidateAccessToken',
    LOGIN = 'authentication/login',
    LOGOUT = 'authentication/logout',
    REGISTER = 'authentication/register',
    TRAINING_ADD = 'training/add',
    TRAINING_EDIT = 'training/edit',
    TRAINING_GET = 'training/get',
    TRAINING_GET_LIST_NAME = 'catalog/training-list',
}
