export const enum LayoutConfig {
    BUTTON_ANDROID = 'Android OS',
    BUTTON_APPLE = 'Aplle iOS',
    BUTTON_AUTHENTIFICATION_COOGLE = 'Войти через Google',
    BUTTON_RESET_ERROR_BIUNDARY = 'Вернуться на главную',
    BUTTON_REGISTER = 'Войти',
    BUTTON_REGISTER_GOOGLE = 'Регистрация через Google',
    BUTTON_REVIEWS = 'Смотреть отзывы',
    BUTTON_SETTINGS = 'Настройки',
    CARD_FOOTER_LINK = 'Скачать на телефон',
    CARD_FOOTER_TITLE = 'Доступно в PRO-тарифе',
    CHECKBOX_REMEMBER_ME = 'Запомнить меня',
    ERROR_BOUNDARY_TITLE = 'Мы знаем о проблеме и работаем над ее устранением.',
    ERROR_BOUNDARY_SUBTITLE = 'Спасибо за терпение.',
    EXIT = 'Выход',
    HOME = 'Главная',
    INPUT_TEXT_EMAIL = 'e-mail:',
    INPUT_TEXT_PASSWODR = 'Пароль',
    INPUT_TEXT_PASSWORD_CONFIRM = 'Повторите пароль',
    INPUT_TYPE_EMAIL = 'E-mail',
    INPUT_TYPE_PASSWORD = 'Password',
    INPUT_TYPE_PASSWORD_CONFIRM = 'Password confirm',
    LINK_FORGOT_PASSWORD = 'Забыли пароль?',
    TITLE_ONE = 'Приветствуем тебя в CleverFit — приложении,',
    TITLE_TWO = 'которое поможет тебе добиться своей мечты!',
}
