export const enum PathConfig {
    AUTH = '/auth',
    AUTH_CHANGE_PASSWORD = '/auth/change-password',
    AUTH_CONFIRM_EMAIL = '/auth/confirm-email',
    AUTH_GOOGLE = '/auth/google',
    BASE = '/',
    HOME = '/main',
    REGISTRATION = '/auth/registration',
    RESULT = '/result',
    RESULT_ERROR = '/result/error',
    RESULT_ERROR_CHANGE_PASSWORD = '/result/error-change-password',
    RESULT_ERROR_CHECK_EMAIL = '/result/error-check-email',
    RESULT_ERROR_CHECK_EMAIL_NO_EXIST = '/result/error-check-email-no-exist',
    RESULT_ERROR_LOGIN = '/result/error-login',
    RESULT_ERROR_USER_EXIST = '/result/error-user-exist',
    RESULT_SUCCESS = '/result/success',
    RESULT_SUCCESS_CHANGE_PASSWORD = '/result/success-change-password',
}
